spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=hospital_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: Thobani@2272
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        "[format_sql]": true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true

app:
  jwt:
    secret: hospital-management-super-secret-key-minimum-512-bits-long-enough-for-hmac-sha512
    access-token-expiry-ms: 900000
    refresh-token-expiry-ms: 604800000
    issuer: hospital-management